language: node_js
node_js:
    - "10"
install:
    - npm install
script:
    - echo -e "\x1b\x5b35;1m*** Testing...\x1b\x5b0m"
    - npm test
    - echo -e "\x1b\x5b35;1m*** Testing complete...\x1b\x5b0m"
